# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Cognitive computing
author: cc-team
logo: logo.png
copyright: SLO 2022

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: auto

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/keuzethemas/ccbook  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  
sphinx:
  extra_extensions:

#  local_extensions:
#    sphinx_progress: ./ext/sphinx-progress
  config:
    language: nl
    numfig_format:
      exercise: "Opdracht %s"
      assessment: "Vraag %s"
#    graphviz_output_format: "svg"
  
exclude_patterns: [README.md, opmerkingen.md, ext/*,_build, Thumbs.db, .DS_Store, ".ipynb_checkpoints/*", "**.ipynb_checkpoints", figuren/*]
